name: Releaser
on:
  push:
    tags:
      - "*"
jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APP_NAME: gh_code_editors
    runs-on: ubuntu-latest
    permissions: write-all
    name: Create GH Release
    steps:
      - uses: actions/checkout@v3
      - name: Build Artifacts
        run: ./release.sh
      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} ${APP_NAME}_chrome.zip ${APP_NAME}_firefox.zip --generate-notes
