name: Releaser
on:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  release:
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    name: "Create GH Release"
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${GITHUB_REF#refs/*/} -t ${GITHUB_REF#refs/*/} --generate-notes
